### PR TITLE
Avalanche-RL aligned with Avalanche 0.3.1

### PR DESCRIPTION
**Pull request by EliaPiccoli**
First attempt to correct the old version of the repository aligning it with the current version of Avalanche ( #11 ).
This PR is just to link the current work, that may (should) be improved towards the partial final version.

- Used RLScenario from Avalanche.
- Moving from BaseStrategy -> BaseTemplate and some other changes in the structure.
- Logging works partially, I had to add some callbacks that were deleted so probably need some refactoring to align with the current flow.

### CODE REVIEW

**Comment by NickLucche** [comment]
Hey, let me know when you believe you've reached a somewhat stable state. It'd be nice to have working tests to go along with the PR, but let me know in case you can't fix them. I see you've also commented out the continual habitat lab part, I believe we can just drop that for now and bring it back later on once we've figured out a more stable structure for the whole project.
Thanks for your work!

**Comment by EliaPiccoli** [comment]
Hi, thank you for reaching out!
As far as concerns the tests, I was trying to fix them but as I discussed with @AntonioCarta its seems that is using an old version of avalanche-lib hence the errors in the coverage tests:
`ModuleNotFoundError: No module named 'avalanche.training.templates'`.
Moreover, the container is pulled from your fork of the repo (see. [test-coverage-coveralls.yml](https://github.com/ContinualAI/avalanche-rl/blob/ea4516beaaeb1c3ff3562ece24d872b793c6a133/.github/workflows/test-coverage-coveralls.yml#L36)), should that reference be moved to this repository?
There is still some work i will do in the next days for the code, in particular:
- check the correct use of the callbacks
- add test to check the reachability of all callbacks
- add implementation of PNN (https://arxiv.org/abs/1606.04671)
- run some experiments to check the strategies are working fine and agents are learning to solve a particular task.

**Comment by NickLucche** [comment]
Hey, the docker image is actually merely hosted on my dockerhub, it is not a reference to the old fork. Main thing is that I am not pushing the image on each commit to master, which I should be doing by editing the github workflow (I believe I was waiting for a more stable main version to do so..anyway I can easily fix that). 
Thanks for your work, tests look good to me, we need em back asap so you can safely add new features (I would put the PNN one in a different PR tho, and try to split the work in smaller chunks so it's more manageable when merging).

**Review by NickLucche — APPROVED** [review]

**Comment by NickLucche** [comment]
okay I can easily add the missing CI part to github actions, but I must be given admin rights to this repo in order to add secrets (which I would then use to log the github runner to dockerhub).
Alternatively, we could push avalanche-rl image to ContinualAI dockerhub but we would still need someone (@AntonioCarta @AndreaCossu) to add the corresponding dockerhub account passwd as a secret in this repo.

**Comment by AntonioCarta** [comment]
@NickLucche I changed your role to admin. I don't have access to the ContinualAI dockerhub myself, you need @vlomonaco for it.

**Pull request merged**
